[package]
name = "hello"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.79"
console_error_panic_hook = "0.1.7"

[profile.release]
opt-level = "s"
